### ISSUE TITLE
Rewrite build enviroment

### ISSUE THREAD

**Issue by k-morozov** [k-morozov/AppChat#14]
Rewrite script (build enviroment) to python

**Comment by asminimulin** [comment]
I've started working on it.

**Comment by asminimulin** [comment]
Is it necessary to use boost 1.73?
Ubuntu has boost 1.71 in standard repositories. I am sure that rh based distros also has fresh enough boost library in standard repos. It is not a big problem to install it from sources, but using prepared package would be easier, especially when build script already use debian specific package manager to install gtest..
